### ISSUE TITLE
Add other CLI tools?

### ISSUE THREAD

**Issue by gep13** [SeanKilleen/paket-attacket#3]
Perhaps similar to what MyGet offers as per this screenshot?

https://github.com/NuGet/NuGetGallery/pull/4437#issuecomment-317969786

**Comment by SeanKilleen** [comment]
I accept PRs. :) The purpose of this little experimentwas to respond for the Paket community which was the most passionate about seeing these changes. 

Should others want to advocate for a specific client, I'll look into it, but most items otherwise will likely be through PRs. I don't want to add every additional client by default. No problem adding them, but I want to be conscious about it.

**Comment by SeanKilleen** [comment]
I'm going to close this for now since it's a question that I've given an answer to, but let me know if it's not satisfactory and I'll re-open. Thanks!

**Comment by SeanKilleen** [comment]
FYI, after #9 which I just merged it should be a bit easier to add an additional client should someone want to do so. I'll also try to add some `readme` instructions or a `contributing.md` file of some kind.
